add collabora converter
dbx/stencil pull request #2
Opened 2024-03-14 11:04 UTC by davidoff92

2024-03-14 17:16 UTC, mbali requested changes
Kicsit mellément a fejlesztés...
Kb elegendő lett volna a  `jodconverter-remote`-ot behúzni *opcionális* függőségként.

Lásd: https://github.com/jodconverter/jodconverter/wiki/LibreOffice-Remote

A teszt hasznos, de a CollaboreaConverter felesleges, kb annyi lenne, hogy létrehozol egy RemoteOfficeManager-t és  azzal hajtasz végre egy konverziót.

2024-03-14 17:16 UTC, mbali commented on src/main/java/io/github/erdos/stencil/Converter.java
Ez jó, kellhet

2024-03-14 17:16 UTC, mbali commented on src/main/java/io/github/erdos/stencil/Process.java
Ez a módosítás a RemoteOfficeManager használata esetén nem kell..

2024-03-14 17:16 UTC, mbali commented on src/main/java/io/github/erdos/stencil/CachingProcess.java
RemoteOfficeManager használata esetén nem kell a módosítás

2024-03-14 17:16 UTC, mbali commented on src/main/java/io/github/erdos/stencil/ProcessFactory.java
RemoteOfficeManager esetén nem kell

2024-03-14 17:16 UTC, mbali commented on src/main/java/io/github/erdos/stencil/impl/CollaboraConverter.java
Feleslegessé válik

2024-03-14 17:16 UTC, mbali commented on src/test/java/io/github/erdos/stencil/CollaboraConverterTest.java
Ezt írjuk át RemoteOfficeManager-t használó tesztre, és nevezzük át

2024-03-27 09:44 UTC, mbali requested changes

2024-03-27 09:44 UTC, mbali commented on src/main/java/io/github/erdos/stencil/CachingProcess.java
> +import java.net.URL;
Ne hagyjunk benne feleslegessé vált importot

2024-03-27 09:44 UTC, mbali commented on pom.xml
> +    </dependency>
Ez szerintem benn maradt, mintha nem használná új kód

2024-03-28 14:46 UTC, davidoff92 commented on pom.xml
> +    </dependency>
egy tesztben használtam, de most átálltam a tesztben egy másik depenedenciára és ezt töröltem

2024-03-28 14:57 UTC, mbali approved these changes

2024-04-18 09:42 UTC, merged